### ISSUE TITLE
buff/cache usage didn't increase after reaching the RAM size when enable the FLASH storage

### ISSUE THREAD

**Issue by hengku** [JohnSully/KeyDB#114]
I tried a test on the FLASH storage and observed the buff/cache usage didn't increase after reaching the RAM size when typing the "free" command. 

* Successfully complied keydb under Ubuntu 18.04 with:

  make MALLOC=memkind

* All testing machines have 56 cores, 384GB RAM, 2TB Optane SSD, and 10Gbps network

* One machine running a keydb server with "server-threads 1", "server-thread-affinity false", "maxmemory 1500gb" 

  After starting the keydb server, I saw 1.5T used on my SSD partition

* One machine running memtier-benchmark as the following:

  memtier_benchmark -s -p -d 12800 -t 1 -c 1 --key-pattern=P:P -n 100000000 --key-minimum=1 --key-maximum=100000000 --ratio 1:0 --hide-histogram

* From the test case above, I observed the buff/cache usage didn't increase after reaching 380GB when typing the "free" command.  If that test complete, it should populate more than 1TB data to the keydb server, so where are those data after 380GB?

**Comment by JohnSully** [comment]
Hi @hengku 

The kernel has full control over what it chooses to keep in RAM.  The missing data is stored on a file in the path you specified.  If you watch the "df" command you can see your free space decrease as more data is added.  The file itself is immediately unlinked so that it is automatically deleted when the process ends so you won't see it with an "ls" command, but you will see it with lsof or other commands that show open file descriptors.

There are a number of tuning parameters which influence what the kernel chooses to place in memory.  See here for more information: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/tuning_and_optimizing_red_hat_enterprise_linux_for_oracle_9i_and_10g_databases/sect-oracle_9i_and_10g_tuning_guide-memory_usage_and_page_cache-tuning_the_page_cache
