### ISSUE TITLE
keydb-benchmark

### ISSUE THREAD

**Issue by guowangy** [JohnSully/KeyDB#145]
README.md claim that keydb-benchmark is single thread and not suitable for multiple threading testing. But I compile from source code, and see that `keydb-benchmark` can use `-threads N` option for multiple thread.

My question: is `keydb-benchmark` good enough for benchmark, or still recommend to use `memtier` tool?

**Comment by JohnSully** [comment]
At the time the readme was written that option did not exist, we have since pulled that change from Redis.

My testing so far has shown that redis/keydb-benchmark even with multithreading is still not capable of saturating a KeyDB server. So the recommendation continues to be to test with memtier. 

The benchmark tool is used by the test suite to generate traffic and can also be useful for ad hoc testing so I keep it around, even though its not useful for its named purpose.

**Comment by guowangy** [comment]
Got it.
Thanks for your answer.
