### ISSUE TITLE
Bind cores not always starting from the first core

### ISSUE THREAD

**Issue by hengku** [JohnSully/KeyDB#162]
KeyDB binds cores always starting from the first core. Is it possible to bind specific core range? For example, starting from the 11th core.

**Comment by JohnSully** [comment]
That seems easy to add and be backwards compatible.  Instead of yes/no/true/false we can also accept a number for the starting core.

**Comment by JohnSully** [comment]
With change 9e2e2067 this is now implemented.

Instead of passing true/false to server-thread-affinity you can now pass an integer which is the core we will start binding from.  Note that the core numbering starts at 1, as it does in htop.  

Example:
` keydb-server --server-threads 2 --server-thread-affinity 4`

**Comment by hwware** [comment]
Hi John, it works and is compatible with true/false as well. Thanks again!

**Comment by hengku** [comment]
Hi John, it works and is compatible with true/false as well. Thanks again!
