### ISSUE TITLE
role command not working correctly with multiple-masters

### ISSUE THREAD

**Issue by jtorkkel** [JohnSully/KeyDB#165]
Issuing role command when "multiple-masters yes " is active not working as expected. 

Current behavior:
- it show only one connected master at time and next query show next in round robin manner
- after using command once no other command works without disconnecting and reconnecting the CLI.

Expected behavior:
- should list all masters or specified master
- should not prevent using other commands

Version 5.3.3.

Repro steps:
start keydb with  options "--active-replica yes --multi-master yes" and create mesh of for example 4 node.
Issue command "info replication", "role", "role", "role" followed "info replication" and "info"

127.0.0.1:8881> info replication
# Replication
role:active-replica
Master 0:
master_host:127.0.0.1
master_port:8882
master_link_status:up
master_last_io_seconds_ago:0
master_sync_in_progress:0
slave_repl_offset:74370997617
Master 1:
master_host:127.0.0.1
master_port:8883
master_link_status:up
master_last_io_seconds_ago:0
master_sync_in_progress:0
slave_repl_offset:77299923988
Master 2:
master_host:127.0.0.1
master_port:8884
master_link_status:up
master_last_io_seconds_ago:0
master_sync_in_progress:0
slave_repl_offset:77647975158
slave_priority:100
slave_read_only:0
connected_slaves:3
slave0:ip=127.0.0.1,port=8883,state=online,offset=26740698391,lag=1
slave1:ip=127.0.0.1,port=8884,state=online,offset=26744632480,lag=0
slave2:ip=127.0.0.1,port=8882,state=online,offset=26731781910,lag=1
master_replid:8a6333722850e044e71bdb85ebdb129a594c1f05
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:26752190518
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:26751141943
repl_backlog_histlen:1048576
127.0.0.1:8881> role
1) "active-replica"
2) "127.0.0.1"
3) (integer) 8882
4) "connected"
5) (integer) 74462784239
127.0.0.1:8881> role
1) "active-replica"
2) "127.0.0.1"
3) (integer) 8883
4) "connected"
5) (integer) 77399343307
127.0.0.1:8881> role
1) "active-replica"
2) "127.0.0.1"
3) (integer) 8884
4) "connected"
5) (integer) 77746460869
127.0.0.1:8881> info replication
active-replica
127.0.0.1
8882
connected
127.0.0.1:8881> info
active-replica
127.0.0.1
8883
connected
77564175501127.0.0.1:8881>

**Comment by JohnSully** [comment]
Sounds like a similar issue to “config get replicaof”. Sorry we missed this one.

**Comment by JohnSully** [comment]
Fixed in change 888d69a8

Note that the command will return an array of arrays if there is more than one master - this will almost certainly be incompatible with existing software looking at the output of this command.  But they would need to be updated to handle multi master regardless.

For compatibility if there is only one master we return the same format as we always did.

Multiple masters:
127.0.0.1:6379> role
1) 1) "active-replica"
   2) "127.0.0.1"
   3) (integer) 6380
   4) "connected"
   5) (integer) 7660
2) 1) "active-replica"
   2) "127.0.0.1"
   3) (integer) 6381
   4) "connected"
   5) (integer) 7605


Single Master:
127.0.0.1:6379> role
1) "active-replica"
2) "127.0.0.1"
3) (integer) 6380
4) "connected"
5) (integer) 12051
