### ISSUE TITLE
Add TCMalloc to the malloc() providers

### ISSUE THREAD

**Issue by lazerl0rd** [JohnSully/KeyDB#177]
**Is your feature request related to a problem? Please describe.**

Google's TCMalloc is a fast memory allocator, and faster than most of it's alternatives. It reduces lock contention and works well with threads and STL.

**Describe the solution you'd like**

I would like to be able to use TCMalloc as an option when building as specified by `make MALLOC=tcmalloc`.

**Describe alternatives you've considered**

n/a

**Additional context**

https://github.com/gperftools/gperftools
https://gperftools.github.io/gperftools/tcmalloc.html

**Comment by JohnSully** [comment]
Hi @lazerl0rd 

TCMalloc support is currently blocked because tcmalloc does not support overriding the new operator.  I've discussed this with the tcmalloc developers and they've agreed in principal to accept a PR allowing this, however I haven't had a chance to actually go though and implement it.

Issue #122 is already tracking this.
