### ISSUE TITLE
"Multi-Clusters" aka Multi-Datacenter Replicated KeyDB Clusters

### ISSUE THREAD

**Issue by victorstewart** [JohnSully/KeyDB#186]
does anyone have a multi-datacenter KeyDB cluster running?

can multi-master setups jive with super high latencies? like 500ms roundtrip NYC to Sydney?

i'm in the situation where I'm not about to pay a billion dollars per shard for redis enterprise, but I need my database replicated across many datacenters spanning the globe.

so I've built asynchronous replication capabilities into my client (which also boasts compile time RESP serialization from pretty format and lots of other neat features), where essentially any write is simply asynchronously echoed to independent redis clusters running in each datacenter.

but of course there are a litany of fundamental limitations to this approach, which I've spent the day mapping out in my mind, haha. luckily my use cases for the moment work within its limitations.

of course it would be nice to just not have to contemplate these complexities with every new redis command I write in my server code.

so does KeyDB already solve my problem? I didn't see any mention of these issues at first or second glance.

If there's no ability to have "multi-clusters" then a "multi-masters" non-cluster deployment would meet my needs for now (after checking out the performance possible with KeyDB), but eventually I'd need clusters in each datacenter.

**Comment by JohnSully** [comment]
Hi @victorstewart you can use KeyDB with high latencies but you should be aware of the limitations since we don't use CRDTs.

If you just use sets/gets the biggest issue is clients may have a different view of the world, e.g. 
A> set keyA foo
A> set keyA baz
B> set keyB bar
B> get keyB
----> You will get either foo, bar, or baz depending on the timing of the replication messages

If you use lists a bigger issue is the ordering may differ on different clients.

This is not inherent to just high latency but it does make these sorts of cases more likely to be experienced.

**Comment by JohnSully** [comment]
Also I recommend using the community forum for these sorts of issues.  I'm hoping to keep github more for bugs: https://community.keydb.dev/

**Comment by victorstewart** [comment]
Thanks @JohnSully  for calling attention to those artifacts. I explored all such topics in my mind when I designed the replication feature into my client (before deciding not to go that way). Luckily the majority of my keys are "single client owned" and I have no ordered lists.

I'll use the community forum in the future. I just posted my thoughts on the "What should we build next?" thread.
