### ISSUE TITLE
Is it possible to use that software to build your own DBaaS solution or license it on-prem basis?

### ISSUE THREAD

**Issue by mikefaraponov** [JohnSully/KeyDB#20]

**Comment by JohnSully** [comment]
You mean KeyDB?

KeyDB is released under the 3-clause BSD license which allows you to run it for whatever purpose without charge.  That includes using it for commercial purposes.  If you do use KeyDB in a product I'd love to know about it - but that is not required by the license.

The exact license is below:

Copyright (c) 2006-2015, Salvatore Sanfilippo
Copyright (C) 2019, John Sully
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Redis nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by JohnSully** [comment]
Please reopen if this doesn't answer your question.

**Comment by mikefaraponov** [comment]
So I am done with https://app.scalablespace.com currently it's mvp, but I am going to implement more features, more OSS databases (postgresql, maybe, rabbitmq or smth like that)
