### ISSUE TITLE
Specified 4 threads but keydb 6.0.8 worked as single thread

### ISSUE THREAD

**Issue by hengku** [JohnSully/KeyDB#208]
I specified 4 threads in keydb.conf and started the keydb-server, but it just used 1 core when I checked the cpu usage. As a result, the QPS is the same as a single thread keydb. I tried on both x86 servers and ARM servers, and it showed the same behavior. 

![图片](https://user-images.githubusercontent.com/56440979/85624680-4927f280-b638-11ea-9da8-a13ab336a53c.png)

![图片](https://user-images.githubusercontent.com/56440979/85624883-960bc900-b638-11ea-826b-15953c2db72c.png)

![图片](https://user-images.githubusercontent.com/56440979/85625109-eb47da80-b638-11ea-865a-9303658dfa68.png)

**Comment by JohnSully** [comment]
Hi @hengku  KeyDB will try to keep at least 50 clients on a thread before allocating to other threads.  This bunching reduces overhead from locking.  The default is tuned for relatively fast X86 systems and assumes normal workloads.

If this default is not suitable for your workload you can use the "min-clients-per-thread" configuration to reduce the number, or set it to zero in order to completely disable this feature.

**Comment by hengku** [comment]
Thank you @JohnSully , it worked well after I added and set "min-clients-per-thread" to zero in keydb.conf. Just curious why this parameter in not included in keydb.conf by default or mentioned in some doc?

**Comment by JohnSully** [comment]
Leaving open to address doc fixes.

**Comment by JohnSully** [comment]
Documented in change 1b9ade7f

This will also make its way to the website.
