### ISSUE TITLE
 NOTICE: Detuning locks due to high load per core

### ISSUE THREAD

**Issue by macropin** [JohnSully/KeyDB#262]
**Describe the bug**
We're seeing numerous log entries related to "Detuning locks". 

```
1:12:S 25 Nov 2020 04:47:25.563 # NOTICE: Detuning locks due to high load per core: 97.49%
1:12:S 25 Nov 2020 04:47:55.668 # NOTICE: CPU pressure reduced
```

These logs are being printed when running KeyDB under Kubernetes on a moderately busy cluster. The pods have more than sufficient CPU requests.

What are the implications of the locks changing from `__ATOMIC_RELEASE` to `__ATOMIC_RELAXED`?

**Comment by JohnSully** [comment]
The acquire/release semantics aren’t important for the detune. The meaning of this message is that KeyDB is attempting to gracefully handle a CPU overcommit situation. 

KeyDB uses spinlocks for fast synchronization. When CPU load is above 100% per core the kernel may unwittingly give CPU time to a blocked thread that is spin waiting instead of the active thread. This results in much higher latency. 

Instead when this situation is detected KeyDB will spin for a shorter time before putting a thread to sleep. This results in better throughput when CPU time is limited. However the “proper” fix is to ensure CPU time is not so constrained. 

If you aren’t on the latest version I’d recommend updating as we’re much more efficient with CPU usage in the latest version. This may solve your CPU load issues without upgrading hardware.

**Comment by macropin** [comment]
Does this mean that when there is perceived CPU pressure KeyDB is less consistent when running in multi-master?

**Comment by JohnSully** [comment]
No this does not affect consistency - just performance. If your clients are getting acceptable latency then this log may be ignored. If not then the correct fix is to reduce cpu load on the system.

**Comment by spagu** [comment]
In my case, I cannot add keyDB into stacks or pods due to a simple problem: CPU is calculated via all available CPUS on a node (8CPU/16CPU), not those dedicated to the container. This means other apps when touch 105% - keydb is lost.
