### ISSUE TITLE
Section addressing non-serialiazability of a multithreaded redis

### ISSUE THREAD

**Issue by borg286** [JohnSully/KeyDB#4]
A significant reason is great is that scripts and MULTI-EXEC commands are isolated from other clients making it easy to reason about transactions. This comes from the single threaded nature of redis. I didn't find a section in your README addressing the concern that KeyDB would allow 2 transactions to run concurrently.

**Comment by JohnSully** [comment]
KeyDB provides the same guarantees here as Redis does, namely that EXEC transactions are atomic.  Single threading is not required in order to have transactions.  If you find a bug where we don't uphold this guarantee that would be an extremely high priority item to fix.

Lua scripts and external modules hold a lock and prevent any other code from running concurrently so they also maintain the same guarantees as before.  API changes are required in order to gain more concurrency here and if it is a big enough problem we may look at that in the future.

I'm reticent to add a section to the ReadMe that effectively says "we're not broken" but if its a common source of confusion it may be necessary.

**Comment by JohnSully** [comment]
#5 is very similar to this issue, and because of that I've added extra phrasing to the Readme:

KeyDB has full compatibility with the Redis protocol, modules, and scripts. This includes full support for transactions, and atomic execution of scripts.

**Comment by JohnSully** [comment]
Additional architecture information added: 8a5a513662d1eaeaf9887584a415d5e1bca06681

**Comment by JohnSully** [comment]
Please reopen if you feel this has not been addressed fully.
