### ISSUE TITLE
some clarifications regarding replication 

### ISSUE THREAD

**Issue by silviucpp** [JohnSully/KeyDB#40]
Hello,

I need few clarifications regarding the active-active replication and the performance impact.

1. The replication is async ?

For example I have 2 datacenters, in each datacenter for each shard I'm planning to add 2 nodes in active- active replication.

Each shard in DC1 will have an associated shard in DC2 as well with the same number of nodes.

So in the end each redis node from a shard will have 3 replicas (1 in the same dc and 2 in the other dc).

In case the replication is sync the performance impact will be high so this is my biggest concern in this moment comparing with
the https://github.com/Netflix/dynomite where the replication is async.

2. How fail-over works ?

Let's suppose one node goes down. While is down the clients will send the read/writes to the other replicas.
After some time the node is fixed and started back. The node will accept connections from clients only after it's in sync with the other replicas ?

Because otherwise the clients can start connecting to it and send requests to keys that were not already propagated from replicas

Kind regards,
Silviu

**Comment by jonathanleang** [comment]
I am also thinking about switching from /Netflix/dynomite because split brain issue with dynomite and don't want to add dynomite-manager.

My use case is 3 DC (US/EU/ASIA), 3 redis servers, all set up as master read/write and use dynomite to sync to the other DC, and when one of the server drops out, dynomite doesn't reshare the missing data.. 

KeyDB's Active-Active Replication is the killer feature, keep up the good work John.

I am just waiting for 1.0 to try it out on our prod system. 

Btw, how to import data from existing redis ? Can KeyDB just use Redis's dump.rdb ?

**Comment by JohnSully** [comment]
1. The replication is async?

Yes, replication is async (as it is with standard Redis replication).  If you write to both masters before they are able to synchronize the last write (wall clock time) will win when the backlog is reconciled.  I'm very interested in alternative options here - but I don't want to guess at what people need.  If you have any ideas to make this work better for your use case please let me know.

2. How does fail-over work?

When the link with the other master is severed a backlog of writes will be kept along with the timestamps of those writes.  When the other master rejoins the two databases will be merged with a last write wins policy.  This means you can still write to either node when the link between them is severed and keep your data.

The primary synchronization primitive is your servers clock.

Let me know if you have any more questions or ideas on how this can be improved.

**Comment by JohnSully** [comment]
Also jonathan,

> Btw, how to import data from existing redis ? Can KeyDB just use Redis's dump.rdb ?

KeyDB can read your Redis rdb file and redis should be able to read KeyDB's.  If you hit an error its a bug, so please open an issue.

**Comment by JohnSully** [comment]
I was thinking more for crazier modules like modssl: https://github.com/JohnSully/modssl That use internal Redis functionality outside of the public API.  If they run on a version without the necessary internal function they could fallback to an internal one.

Its not something I particularly want to support (modssl is just a demo) but I am curious if any modules do call private APIs - and what the implications of this for those are.  I'm going to do a test with some of the more popular ones fairly soon.

**Comment by silviucpp** [comment]
@JohnSully when using both active-active and multi master it's normal that all nodes reports role:slave ?

**Comment by kaizen1** [comment]
> 1. The replication is async?
> 
> Yes, replication is async (as it is with standard Redis replication). If you write to both masters before they are able to synchronize the last write (wall clock time) will win when the backlog is reconciled. I'm very interested in alternative options here - but I don't want to guess at what people need. If you have any ideas to make this work better for your use case please let me know.
> 
As a Redis user (product architect not a coder), I love the idea of this project. Sharding is a big operational headache so KeyDB looks great. Keep it up. Hope it thrives.

In a similar drive for simplicity of operations, we also use master-master MariaDB w/ Galera option. All data is the same everywhere. Backup is only needed on one machine. Easy-Peasy. 

Galera uses a cluster-wide lock on writes and leverages auto-increment keys to avoid collisions. Clients that fail to get a lock simply retry or handle the error on the client. Not exactly apt for Redis data but something to think about. 

More apt is that some Galera users use HAProxy to write to a SINGLE master node (others marked in HAProxy as standby in case of failure). That way we KNOW that there can never be a write collisions  and we never have to worry about losing a server and then having data migrating itself in some magical way all over hell's creation to other "slots" in a shared architecture. Hairball anyone? We like fire and forget. Similarly for KeyDB, I would use a single write master with many read servers (all master-master) since the throughput is so high according to you benchmarks. My guess is that few use cases will ever need to write to more than 1 master, unless you're facebook or netflix, which we're not :). HAProxy + KeyDB. Gonna give it a go...

**Comment by JohnSully** [comment]
@silviucpp I opened issue #45 to track updating the INFO command.

**Comment by OstryDzik** [comment]
@JohnSully Thank you for clarification regarding writes sync after node failure, however could you please elaborate a bit about:

> Let's suppose one node goes down. While is down the clients will send the read/writes to the other replicas.
> After some time the node is fixed and started back. The node will accept connections from clients only  after it's in sync with the other replicas ?
>
> Because otherwise the clients can start connecting to it and send requests to keys that were not  already propagated from replicas

**Comment by kaizen1** [comment]
...the other problem is when keys are deleted while one node is down and then it comes back up. Those deleted keys should also be deleted from the down node when it comes back up. Same is true for evictions based on TTL that may have expired.

**Comment by OstryDzik** [comment]
I do not think that this would be a problem. When the failed node comes up,
it's data is replicated from scratch from the other one, so deleted keys
stay deleted :-) my only concern is the read inconsistency that may happen
in the time window between rebooting failed node and completing
replication.

sob., 29 cze 2019, 20:16 użytkownik kaizen1 <notifications@github.com>
napisał:

**Comment by kaizen1** [comment]
Not sure "from scratch" is true. I'd like to hear from maintainers on that point.

**Comment by OstryDzik** [comment]
Fair point, I assumed in-memory storage without persistency. Let's wait for
John.

sob., 29 cze 2019, 20:50 użytkownik kaizen1 <notifications@github.com>
napisał:

**Comment by daledude** [comment]
@JohnSully probably missed comments after ticket closed.
