### ISSUE TITLE
Replication information not available, can't generate the RDB file right now

### ISSUE THREAD

**Issue by piscopoc** [JohnSully/KeyDB#56]
We are running a two master setup in active-active mode, both instances crashed a few hours ago after running fine for about a week and now I am trying to get them back in sync. I started one of the master's and then proceeded to start the second master after the AOF file from the first master was loaded (I did remove the AOF file from the second master in order to get a clean state). After several attempts with the second master to sync with the first master I am now getting this error: (which loops indefinitely) 

```
1:S 14 Jul 2019 19:52:41.104 * MASTER <-> REPLICA sync started
1:S 14 Jul 2019 19:52:41.104 * Non blocking connect for SYNC fired the event.
1:S 14 Jul 2019 19:52:41.105 * Master replied to PING, replication can continue...
1:S 14 Jul 2019 19:52:41.106 * Partial resynchronization not possible (no cached master)
1:S 14 Jul 2019 19:52:41.106 * Master does not support PSYNC or is in error state (reply: -ERR BGSAVE failed, replication can't continue)
1:S 14 Jul 2019 19:52:41.106 * Retrying with SYNC...
1:S 14 Jul 2019 19:52:41.106 # I/O error reading bulk count from MASTER: Resource temporarily unavailable
1:S 14 Jul 2019 19:52:41.662 * Replica XX.XX.XX.XXX:6380 asks for synchronization
1:S 14 Jul 2019 19:52:41.662 * Full resync requested by replica XX.XX.XX.XXX:6380
1:S 14 Jul 2019 19:52:41.662 * Starting BGSAVE for SYNC with target: disk
1:S 14 Jul 2019 19:52:41.662 # BGSAVE for replication: replication information not available, can't generate the RDB file right now. Try later.
1:S 14 Jul 2019 19:52:41.662 # BGSAVE for replication failed
...
BGSAVE for replication: replication information not available, can't generate the RDB file right now. Try later.
```

What is the preferred approach to recovering from a crash in an active-active replication setup?

**Comment by JohnSully** [comment]
This issue occurs when the Active Replicas attempt to connect to each other while a sync is in progress.

To workaround the issue follow this procedure:
1) Bring up host1
2) Bring up host2
3) host1> replicaof host2
**Wait For the Syncronization to Complete and you see: MASTER <-> REPLICA sync: Finished with success in the log**
4) hos2> replicaof host1

I will fix the underlying issue so you do not need to rely on this procedure and update this bug when that is complete.

**Comment by JohnSully** [comment]
Also for a little background on the issue:

When both clients want to reconnect with each other at the same time there is a race condition as only one can sync at a time.  Eventually the jitter between the two clients allows one to win and synchronization will begin.  While this process plays out both will display an error message repeatedly.  Once one client wins it will stop displaying an error message however the remaining client will continue to complain once per second until it has a chance to synchronize after the winner finishes.

The fix for this issue will be to make the negotiation of which client goes first more formal, and to stop displaying error messages for what is an expected procedure.

**Comment by PurpleIsEverything** [comment]
We fight with this regularly when restarting/updating instances. Getting everything running is quite a pain.

**Comment by JohnSully** [comment]
I plan to have a fix out by Friday. 

The goal of Active Replication is to not require a fancy sync process. So this is most definitely a bug.

**Comment by PurpleIsEverything** [comment]
Will we have to take down our entire cluster for this update? Seems like a significant change.

**Comment by JohnSully** [comment]
No need to take everything down - you will be able to swap nodes one at a time. It is possible to fix this with backwards compatibility.

**Comment by JohnSully** [comment]
This is now fixed in change bb090b6d2 which is in unstable and RELEASE_5.  If no blocking bugs are discovered RELEASE_5 will be officially released on Monday.

The fix was much simpler than I originally thought.  Traditional replicas need to know their masters database ID before they can generate their own RDB files so that the REPL backlog applies to the correct database.  However because Active-Replicas are both simultaneously slaves and masters they maintain their own repl log with their own selected database.  In the RDB save codepath we should be using our own slavedb number, not that of our master.

Once this change is made the dependency on a connection with the remote master is broken and the active-replica can generate its RDB at any time.  This fixes the error message you see in this bug.

There was no user-bad from this underlying issue if all replicas were active (since they don't use this field when loading), however if a non-active replica was connected it could have resulted in changes being applied to an incorrect database.

This change is fully backwards compatible with older active-replicas.

**Comment by PurpleIsEverything** [comment]
Went ahead and tried this new build tonight however seems like the container tagged latest on Docker currently won't start with the following error: ``standard_init_linux.go:211: exec user process caused "exec format error"``

**Comment by piscopoc** [comment]
@JohnSully just wanted to follow up and say thanks for fixing this issue. Deployed v0.9.6 last night and was up and running in less than 5 minutes. Thanks again!

**Comment by benschermel** [comment]
There was an issue with the docker manifest. this should be fixed now when you pull latest.
