### ISSUE TITLE
Replicating data to db:0

### ISSUE THREAD

**Issue by digipigeon** [JohnSully/KeyDB#80]
Clean deployment tested in both the master and VERSION_5

fairly stock config with the exception of
```
active-replica yes
```

Inserting data using `ioredis` (NodeJS) into `db 11` on the primary works as expected, but when viewed on the replica data appears in `db 0`

I have attempted to replicate the bug with manual inserts with both Redis Desktop Manager and the `keydb-cli` but with no luck.

I am confident that this error is not related to `ioredis` as this is the same library and deployment we are using in production with an existing Redis server and the data correctly appears on the primary/master.

**Comment by digipigeon** [comment]
Just to elaborate on the the steps required for reproducing this error.

Single Manual inserts did not trigger this to replicated into the wrong database, even from `ioredis`

When doing both multi and just sequentially operations (e.g 10's - 100's of `sadd` per second), this is when the problem happens.

**Comment by JohnSully** [comment]
Hi @digipigeon 

This issue is bad enough I've drafted a new release with the fix.  v5.0.2 has just been released although it may take a few hours for docker to update.  Active Replica's run remote commands through the new RREPLAY command which is why only Active Replication is affected - this was not correctly persisting the selected database in some situations.

Sorry for any trouble this has caused you and thanks for the bug report!

Fix change: 50a6a3ca389aef3d8f970faef5336f7053cf4cc5

**Comment by digipigeon** [comment]
I am sorry to report that this problem does not appear to be fixed completely.

Immediate results are good, this everything appears to be correct. However after reading and writing on just server A (checking back after 3 hours), the results on server B are not congruent, we are seeing information leak between databases and also appearing in db0 (which we decided to avoid using just in case).

Furthermore, data is persisting as well (TTL's being set, possibly in a separate operation) are not been respected, meaning this data we are accumulating is not being deleted and making things very difficult to correct.

**Comment by JohnSully** [comment]
It looks like there may be multiple issues so I will keep investigating.  

I understand the frustration. This is a high priority bug, and I need to expand the testing around multi db scenarios.

**Comment by digipigeon** [comment]
Can we please have this ticket re-opened so it does not get lost. Thank you.

**Comment by JohnSully** [comment]
I've refactored RREPLAY to take an explicit database ID argument.  This way the master no longer needs to track the replica's selected DB.  Its a much simpler design that eliminates the potential for bugs.  This change is backwards compatible with older versions so that you can live upgrade.

Change: 6e1e5bd08 target is v5.1 which I'm planning to release in the next few days.

Note: You mention expiration issues, because of the DB issue its hard to say if its a dupe or a new issue.  We do have tests validating expiration with active replication; however its possible there are issues when under high load.  If this issue reappears please open another bug.

**Comment by digipigeon** [comment]
Unable to test the issue as I tried a deployment today and the build is unstable. I will try to find some time to get some back traces, etc and raise a new issue ticket.
