### ISSUE TITLE
Alpine-powered docker container

### ISSUE THREAD

**Issue by dinamic** [JohnSully/KeyDB#95]
It would be awesome if we have an official Alpine Linux container. It would be way smaller than the one we've got today.

Could you think of any issues that would prevent KeyDB from running in Alpine?

Note: I would appreciate if the builds in Docker hub are automated, giving us somewhat guarantee that this is the exact Dockerfile that was used for creating the image.

**Comment by JohnSully** [comment]
I haven't tested building with MUSL and I don't have the bandwidth to actively test Alpine Linux.  That said I will fix any issues that may be encountered if someone wants to take on support and testing for that distro.  Using Musl instead of glibc is likely to be the biggest issue.

Having docker do the build is a possibility but since we have multiple release targets we wanted to ensure they all had the same build pipeline for simplicity.  We can revisit that in the future.
